# Generated by Django 4.1.7 on 2023-03-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='about_me',
            field=models.TextField(max_length=300, null=True, verbose_name='Информация о пользователе'),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=12, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='account',
            name='sex',
            field=models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=50, null=True, verbose_name='Пол'),
        ),
    ]
